# Generated by Django 6.0 on 2026-02-28 14:12

import api.models.fighter
import api.models.utils
import api.options
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.models.utils.user_image_upload_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufcstats_event_id', models.CharField(blank=True, db_index=True, help_text='UFCStats.com event ID for tracking source data', max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufcstats_fighter_id', models.CharField(blank=True, db_index=True, help_text='UFCStats.com fighter ID for tracking source data', max_length=50, null=True, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('sname', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_class', models.CharField(choices=[('SW', 'Strawweight'), ('FLY', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Catchweight')], max_length=255)),
                ('dob', models.DateField()),
                ('stance', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reach', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, countries=api.options.CustomCountries, max_length=3, null=True)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('draws', models.PositiveSmallIntegerField(default=0)),
                ('no_contests', models.PositiveSmallIntegerField(default=0)),
                ('dqs', models.PositiveSmallIntegerField(default=0)),
                ('slpm', models.DecimalField(blank=True, decimal_places=2, help_text='Significant Strikes Landed per Minute', max_digits=5, null=True)),
                ('str_acc', models.PositiveSmallIntegerField(blank=True, help_text='Striking Accuracy %', null=True)),
                ('sapm', models.DecimalField(blank=True, decimal_places=2, help_text='Significant Strikes Absorbed per Minute', max_digits=5, null=True)),
                ('str_def', models.PositiveSmallIntegerField(blank=True, help_text='Strike Defense %', null=True)),
                ('td_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Takedown Average per 15min', max_digits=5, null=True)),
                ('td_acc', models.PositiveSmallIntegerField(blank=True, help_text='Takedown Accuracy %', null=True)),
                ('td_def', models.PositiveSmallIntegerField(blank=True, help_text='Takedown Defense %', null=True)),
                ('sub_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Submission Average per 15min', max_digits=5, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.models.fighter.fighter_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('UFC', 'Ultimate Fighting Championship'), ('PFL', 'Professional Fighters League'), ('Bellator', 'Bellator MMA'), ('ONE', 'ONE Championship')], max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.models.utils.promotion_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_predictions', models.IntegerField(default=0)),
                ('winner_correct_count', models.IntegerField(default=0)),
                ('perfect_prediction_count', models.IntegerField(default=0)),
                ('winner_and_decision_correct_count', models.IntegerField(default=0)),
                ('winner_and_finish_correct_count', models.IntegerField(default=0)),
                ('winner_and_method_correct_count', models.IntegerField(default=0)),
                ('winner_and_round_correct_count', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufcstats_fight_id', models.CharField(blank=True, db_index=True, help_text='UFCStats.com fight ID for tracking source data', max_length=50, null=True, unique=True)),
                ('fighter_red_record', models.JSONField(blank=True, max_length=50, null=True)),
                ('fighter_blue_record', models.JSONField(blank=True, max_length=50, null=True)),
                ('weight_class', models.CharField(choices=[('SW', 'Strawweight'), ('FLY', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Catchweight')], max_length=255)),
                ('scheduled_rounds', models.PositiveSmallIntegerField(default=3)),
                ('is_title_fight', models.BooleanField(default=False)),
                ('is_main_event', models.BooleanField(default=False)),
                ('card_tier', models.CharField(choices=[('MAIN_CARD', 'Main Card'), ('PRELIMS', 'Prelims'), ('EARLY_PRELIMS', 'Early Prelims')], default='MAIN_CARD', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=255)),
                ('winning_method', models.CharField(blank=True, choices=[('FINISH', 'Finish'), ('KO/TKO', 'Kotko'), ('DEC', 'Dec'), ('DEC-SPLIT', 'Split'), ('SUB', 'Sub'), ('KO', 'Ko'), ('DQ', 'Dq'), ('NC', 'Noc')], max_length=255, null=True)),
                ('winning_round', models.IntegerField(blank=True, null=True)),
                ('method_details', models.CharField(blank=True, help_text="Detailed method description (e.g., 'Punches to Head')", max_length=255, null=True)),
                ('fight_time', models.CharField(blank=True, help_text="Time of finish (e.g., '2:23')", max_length=10, null=True)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('fighter_red_stats', models.JSONField(blank=True, help_text='Complete statistics for red corner fighter', null=True)),
                ('fighter_blue_stats', models.JSONField(blank=True, help_text='Complete statistics for blue corner fighter', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event')),
                ('fighter_blue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_corner', to='api.fighter')),
                ('fighter_red', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_corner', to='api.fighter')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.fighter')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.promotion'),
        ),
        migrations.AddField(
            model_name='event',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.promotion'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('predicted_method', models.CharField(blank=True, choices=[('FINISH', 'Finish'), ('KO/TKO', 'Kotko'), ('DEC', 'Dec'), ('DEC-SPLIT', 'Split'), ('SUB', 'Sub'), ('KO', 'Ko'), ('DQ', 'Dq'), ('NC', 'Noc')], max_length=255, null=True)),
                ('predicted_round', models.IntegerField(blank=True, null=True)),
                ('winner_correct', models.BooleanField(blank=True, null=True)),
                ('method_correct', models.BooleanField(blank=True, null=True)),
                ('round_correct', models.BooleanField(blank=True, null=True)),
                ('finish_correct', models.BooleanField(blank=True, null=True)),
                ('decision_correct', models.BooleanField(blank=True, null=True)),
                ('perfect_prediction', models.BooleanField(blank=True, null=True)),
                ('points_potential', models.IntegerField(blank=True, default=0)),
                ('points_earned', models.IntegerField(blank=True, default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fight')),
                ('predicted_winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fighter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'fight'), name='one_prediction_per_user_per_fight')],
            },
        ),
    ]
