# Generated by Django 6.0 on 2026-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='card_position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fight order on card (1=main event, 2=co-main, etc.)', null=True),
        ),
    ]
