# Generated by Django 6.0 on 2026-03-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fight_card_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='weight_class',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SW', 'Strawweight'), ('FLY', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Catchweight')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fight',
            name='winning_method',
            field=models.CharField(blank=True, choices=[('KO', 'Ko'), ('TKO', 'Tko'), ('KO/TKO', 'Kotko'), ('SUB', 'Sub'), ('DEC', 'Dec'), ('DEC-U', 'Dec U'), ('DEC-MAJ', 'Dec Maj'), ('DEC-SPLIT', 'Dec Split'), ('DRAW', 'Draw'), ('DRAW-U', 'Draw U'), ('DRAW-MAJ', 'Draw Maj'), ('DRAW-SPLIT', 'Draw Split'), ('DQ', 'Dq'), ('NC', 'Nc'), ('FINISH', 'Finish'), ('UNKNOWN', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SW', 'Strawweight'), ('FLY', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Catchweight')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_method',
            field=models.CharField(blank=True, choices=[('KO', 'Ko'), ('TKO', 'Tko'), ('KO/TKO', 'Kotko'), ('SUB', 'Sub'), ('DEC', 'Dec'), ('DEC-U', 'Dec U'), ('DEC-MAJ', 'Dec Maj'), ('DEC-SPLIT', 'Dec Split'), ('DRAW', 'Draw'), ('DRAW-U', 'Draw U'), ('DRAW-MAJ', 'Draw Maj'), ('DRAW-SPLIT', 'Draw Split'), ('DQ', 'Dq'), ('NC', 'Nc'), ('FINISH', 'Finish'), ('UNKNOWN', 'Unknown')], max_length=255, null=True),
        ),
    ]
