# Generated by Django 6.0 on 2026-03-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fight_weight_class_alter_fight_winning_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
