# Generated by Django 6.0 on 2026-03-05 23:53

import api.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fighter_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.utils.event_image_upload_path),
        ),
    ]
