# Generated by Django 6.0 on 2026-02-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fighter_height_fighter_reach_alter_fighter_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='card_tier',
            field=models.CharField(choices=[('MAIN_CARD', 'Main Card'), ('PRELIMS', 'Prelims'), ('EARLY_PRELIMS', 'Early Prelims')], default='MAIN_CARD', max_length=255),
        ),
    ]
