#!/usr/bin/env bash
# Quick start guide for UFC Scraper

echo "=== UFC Scraper Quick Start ==="
echo ""
echo "1. Install dependencies:"
echo "   /home/etnseca/raptor_env/bin/python -m pip install -r requirements.txt"
echo ""
echo "2. Run demo:"
echo "   /home/etnseca/raptor_env/bin/python demo.py"
echo ""
echo "3. Common commands:"
echo "   # Scrape specific fighter"
echo "   /home/etnseca/raptor_env/bin/python main.py --fighter 'Sean Strickland'"
echo ""
echo "   # Scrape specific fight"
echo "   /home/etnseca/raptor_env/bin/python main.py --fight-id 8d740c844353ae0e"
echo ""
echo "   # Update all upcoming events"
echo "   /home/etnseca/raptor_env/bin/python main.py --update-events"
echo ""
echo "   # Update recent events (last 7 days)"
echo "   /home/etnseca/raptor_env/bin/python main.py --update-recent 7"
echo ""
echo "   # Show scraping status"
echo "   /home/etnseca/raptor_env/bin/python main.py --status"
echo ""
echo "4. View scraped data:"
echo "   cat data/events.json | python3 -m json.tool"
echo "   cat data/fights/8d740c844353ae0e.json | python3 -m json.tool"
echo "   cat data/fighters/0d8011111be000b2_sean_strickland.json | python3 -m json.tool"
echo ""
echo "5. For Django integration, see README.md"
